baseURL = "http://clissoldttc.co.uk/"
languageCode = "en-gb"
title = "Clissold Table Tennis Club"
theme = "clissoldttc"

sectionPagesMenu = "main"

[params]
  description = "clissold park table tennis club"
  gaID = "UA-125718074-1"

[[menu.main]]   
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "News"
  weight = 20
  identifier = "news"
  url = "/news"