baseURL = "http://clissoldttc.co.uk/"
languageCode = "en-gb"
title = "Clissold Table Tennis Club"
theme = "clissoldttc"

sectionPagesMenu = "main"

[params]
  description = "clissold park table tennis club"

[[menu.main]]        
  name = "News"
  weight = 20
  identifier = "news"
  url = "/news"