version: 2
jobs:
  build:
    docker:
      - image: desbo/clissoldttc-build-agent
    steps:
      - checkout
      - run:
          name: Build site
          command: hugo
      - run:
          name: Upload to S3
          command: aws s3 sync public s3://clissoldttc.co.uk